/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ApitureBanking from "../../../..";

export interface OverdraftProtectionPatch
    extends ApitureBanking.AbstractBody,
        ApitureBanking.OverdraftProtectionFields {}
