/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ApitureBanking from "../../../..";

export interface InstitutionsGetCutoffTimesRequest {
    /**
     * Identifies the time zone for formatting time values in the response. If omitted, time values are formatting in the local timezone of the financial institution.
     */
    timeZoneId?: ApitureBanking.TimeZoneId;
    /**
     * The entity tag that was returned in the `ETag` response header of a previous call. If the resource's current entity tag value matches this header value, the `GET` will return 304 (Not Modified) and no response body, else the current resource representation and updated `ETag` is returned.
     */
    ifNoneMatch?: string;
}
