/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Apiture } from "@fern-api/apiture";

export interface ListTransferScheduleRequest {
    /**
     * The date to use to begin calculations of the transfer schedule in `YYYY-MM-DD` [RFC 3339](https://tools.ietf.org/html/rfc3339) date format.
     */
    startsOn: string;
    /**
     * The date to use to conclude calculations of the transfer schedule in `YYYY-MM-DD` [RFC 3339](https://tools.ietf.org/html/rfc3339) date format.
     */
    endsOn?: string;
    /**
     * The direction of the transfer from the institution to the customer used for adjusting transfer dates due to banking holidays. For `debit`, dates are adjusted to the next business day. For `credit`, dates are adjusted to the previous business day.
     */
    direction: Apiture.TransferScheduleDirection;
    /**
     * The maximum amount of dates to calculate and include in the response. If an end date is provided, the total count may be lower than the requested count.
     */
    count?: number;
    /**
     * The interval at which the money movement recurs.
     */
    frequency: Apiture.TransferFrequency;
}
