/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Apiture } from "@fern-api/apiture";

export interface LookUpInstitutionByLocatorRequest {
    /**
     * The financial institution lookup key (routing number, IBAN, or SWIFT/BIC), as indicated by the `locatorType` query parameter.
     */
    locator: string;
    /**
     * Indicates what type of value the `locator` query parameter is.
     */
    locatorType: Apiture.InstitutionLocatorType;
    /**
     * The country code in which to search for institutions. For the US, the `locatorType` must be `abaRoutingNumber`. For non-US countries, the `locatorType` must be `swiftBicCode` or `ibanAccountNumber`.
     */
    countryCode: string;
    /**
     * If looking up a beneficiary institution for a wire transfer beneficiary institution, request the response also include a list of intermediary institutions.
     */
    includeIntermediaryInstitutions?: boolean;
}
