/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";
import { Apiture } from "@fern-api/apiture";

export class BadRequest extends errors.ApitureError {
    constructor(body: Apiture.ProblemResponse) {
        super({
            message: "BadRequest",
            statusCode: 400,
            body: body,
        });
        Object.setPrototypeOf(this, BadRequest.prototype);
    }
}
