/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";
import { ApitureApi } from "@fern-api/apiture";

export class Forbidden extends errors.ApitureApiError {
    constructor(body: ApitureApi.ProblemResponse) {
        super({
            message: "Forbidden",
            statusCode: 403,
            body: body,
        });
        Object.setPrototypeOf(this, Forbidden.prototype);
    }
}
