/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";
import { Apiture } from "@fern-api/apiture";

export class Forbidden extends errors.ApitureError {
    constructor(body: Apiture.ProblemResponse) {
        super({
            message: "Forbidden",
            statusCode: 403,
            body: body,
        });
        Object.setPrototypeOf(this, Forbidden.prototype);
    }
}
