/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";
import { ApitureApi } from "@fern-api/apiture";

export class InternalServerError extends errors.ApitureApiError {
    constructor(body: ApitureApi.ProblemResponse) {
        super({
            message: "InternalServerError",
            statusCode: 503,
            body: body,
        });
        Object.setPrototypeOf(this, InternalServerError.prototype);
    }
}
