/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";
import { Apiture } from "@fern-api/apiture";

export class MethodNotAllowed extends errors.ApitureError {
    constructor(body: Apiture.ProblemResponse) {
        super({
            message: "MethodNotAllowed",
            statusCode: 405,
            body: body,
        });
        Object.setPrototypeOf(this, MethodNotAllowed.prototype);
    }
}
