/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";
import { ApitureApi } from "@fern-api/apiture";

export class NotFound extends errors.ApitureApiError {
    constructor(body: ApitureApi.ProblemResponse) {
        super({
            message: "NotFound",
            statusCode: 404,
            body: body,
        });
        Object.setPrototypeOf(this, NotFound.prototype);
    }
}
