/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";
import { Apiture } from "@fern-api/apiture";

export class NotFound extends errors.ApitureError {
    constructor(body: Apiture.ProblemResponse) {
        super({
            message: "NotFound",
            statusCode: 404,
            body: body,
        });
        Object.setPrototypeOf(this, NotFound.prototype);
    }
}
