/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";
import { Apiture } from "@fern-api/apiture";

export class PreconditionRequired extends errors.ApitureError {
    constructor(body: Apiture.ProblemResponse) {
        super({
            message: "PreconditionRequired",
            statusCode: 428,
            body: body,
        });
        Object.setPrototypeOf(this, PreconditionRequired.prototype);
    }
}
