/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";
import { ApitureApi } from "@fern-api/apiture";

export class PreconditionRequired extends errors.ApitureApiError {
    constructor(body: ApitureApi.ProblemResponse) {
        super({
            message: "PreconditionRequired",
            statusCode: 428,
            body: body,
        });
        Object.setPrototypeOf(this, PreconditionRequired.prototype);
    }
}
