/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";
import { ApitureApi } from "@fern-api/apiture";

export class Unauthorized extends errors.ApitureApiError {
    constructor(body: ApitureApi.ProblemResponse) {
        super({
            message: "Unauthorized",
            statusCode: 401,
            body: body,
        });
        Object.setPrototypeOf(this, Unauthorized.prototype);
    }
}
