/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";
import { Apiture } from "@fern-api/apiture";

export class UnprocessableEntity extends errors.ApitureError {
    constructor(body: Apiture.ProblemResponse) {
        super({
            message: "UnprocessableEntity",
            statusCode: 422,
            body: body,
        });
        Object.setPrototypeOf(this, UnprocessableEntity.prototype);
    }
}
