/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors";
import * as ApitureBanking from "..";

export class ForbiddenError extends errors.ApitureBankingError {
    constructor(body: ApitureBanking.ProblemResponse) {
        super({
            message: "ForbiddenError",
            statusCode: 403,
            body: body,
        });
        Object.setPrototypeOf(this, ForbiddenError.prototype);
    }
}
