/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors";
import * as ApitureBanking from "..";

export class ServiceUnavailableError extends errors.ApitureBankingError {
    constructor(body: ApitureBanking.ProblemResponse) {
        super({
            message: "ServiceUnavailableError",
            statusCode: 503,
            body: body,
        });
        Object.setPrototypeOf(this, ServiceUnavailableError.prototype);
    }
}
