/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors";
import * as ApitureBanking from "..";

export class UnauthorizedError extends errors.ApitureBankingError {
    constructor(body: ApitureBanking.ProblemResponse) {
        super({
            message: "UnauthorizedError",
            statusCode: 401,
            body: body,
        });
        Object.setPrototypeOf(this, UnauthorizedError.prototype);
    }
}
