/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors";
import * as ApitureBanking from "..";

export class UnprocessableEntityError extends errors.ApitureBankingError {
    constructor(body: ApitureBanking.ProblemResponse) {
        super({
            message: "UnprocessableEntityError",
            statusCode: 422,
            body: body,
        });
        Object.setPrototypeOf(this, UnprocessableEntityError.prototype);
    }
}
