/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class ApitureTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, ApitureTimeoutError.prototype);
    }
}
