/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class ApitureBankingTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, ApitureBankingTimeoutError.prototype);
    }
}
