/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ApitureApi } from "@fern-api/apiture";
import * as core from "../../../../core";

export const ChallengeToken: core.serialization.Schema<serializers.ChallengeToken.Raw, ApitureApi.ChallengeToken> =
    core.serialization.string();

export declare namespace ChallengeToken {
    type Raw = string;
}
