/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ApitureApi } from "@fern-api/apiture";
import * as core from "../../../../core";

export const TransferAccountReference: core.serialization.ObjectSchema<
    serializers.TransferAccountReference.Raw,
    ApitureApi.TransferAccountReference
> = core.serialization.object({
    id: core.serialization.lazy(async () => (await import("../../..")).ResourceId),
    label: core.serialization.string().optional(),
    type: core.serialization.lazy(async () => (await import("../../..")).ProductType).optional(),
    location: core.serialization.lazy(async () => (await import("../../..")).AccountLocation).optional(),
});

export declare namespace TransferAccountReference {
    interface Raw {
        id: serializers.ResourceId.Raw;
        label?: string | null;
        type?: serializers.ProductType.Raw | null;
        location?: serializers.AccountLocation.Raw | null;
    }
}
