/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ApitureApi } from "@fern-api/apiture";
import * as core from "../../../../core";

export const TransferRecurrenceType: core.serialization.Schema<
    serializers.TransferRecurrenceType.Raw,
    ApitureApi.TransferRecurrenceType
> = core.serialization.enum_(["fixed", "variable"]);

export declare namespace TransferRecurrenceType {
    type Raw = "fixed" | "variable";
}
