/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ApitureBanking from "../../../..";

export interface NewJointOwnerInvitation
    extends ApitureBanking.AbstractBody,
        ApitureBanking.JointOwnerInvitationFields {}
