/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { ApitureApi } from "@fern-api/apiture";

/**
 * A numeric range for a checking account check number.
 */
export type CheckNumberRange = ApitureApi.PositiveIntegerRange;
