/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The label of a transaction category, such as `"Shopping"`, `"Deposit"`, `"Bill"`, `"Transfer"`, or `"Other"`.
 */
export type TransactionCategoryLabel = string;
