/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Apiture } from "@fern-api/apiture";

/**
 * Collection of transaction categories. The list contains both financial institution defined immutable categories and customer defined categories.
 */
export interface TransactionCategories {
    /** An array containing transaction category items. */
    items: Apiture.TransactionCategory[];
}
