/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { ApitureApi } from "@fern-api/apiture";

/**
 * Summary representation of a transaction resource in transactions collections.
 */
export interface TransactionItem extends ApitureApi.AbstractBody, ApitureApi.TransactionFields {}
