/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Apiture } from "@fern-api/apiture";

/**
 * Summary representation of a transaction resource in transactions collections.
 */
export interface TransactionItem extends Apiture.AbstractBody, Apiture.TransactionFields {}
