/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { ApitureApi } from "@fern-api/apiture";

/**
 * The transaction categorization.
 */
export interface TransactionCategorization {
    label: ApitureApi.TransactionCategoryLabel;
    /** The unique ID of this transaction's category. */
    id: string;
}
