/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Apiture } from "@fern-api/apiture";

/**
 * Collection of transactions. The items in the collection are ordered in the `items` array. The response object may contain the `nextPage_url` pagination link.
 */
export interface Transactions extends Apiture.AbstractPagedBody {
    /** An array containing a page of transaction items. */
    items?: Apiture.TransactionItem[];
    /** The total number of transactions which satisfy the request filters. This is optional and only included if the service can calculate it. */
    count?: number;
}
