/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Describes the merchant associated with a transaction.
 */
export interface TransactionMerchant {
    /** The merchant\'s name. */
    name?: string;
    /** The merchant's website URL. */
    websiteUrl?: string;
    /** The optional URL of the merchant's logo. This image must be an image resource (SVG, PNG, GIF, JPEG image) that does not require any authentication. The URL may contain query parameters. */
    logoUrl?: string;
}
