/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ApitureBanking from "../../../..";

export interface NewTransfer extends ApitureBanking.AbstractBody, ApitureBanking.TransferFields {
    /**
     * This operation may require a completed challenge. If the first attempt calling this operation fails with a 401 `challengeRequired` error, the client should complete the challenge flow as described in the Challenges API, then retry the operation with this `Challenge` request header using the `challengeToken` returned at the end of that flow. If this is passed but the value is invalid, the operation fails with a 401 status code and the `invalidChallengeHeader` problem type.
     */
    challenge?: ApitureBanking.ChallengeToken;
    schedule: ApitureBanking.TransferSchedule;
}
