/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The monetary value, supporting only positive amounts. The numeric value is  represented as a string so that it can be exact with no loss of precision.<br>The schema `monetaryValue` was added on version `0.4.0` of the API.
 */
export type MonetaryValue = string;
