/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Apiture } from "@fern-api/apiture";

/**
 * Representation of a transfer resource.
 */
export interface Transfer extends Apiture.AbstractBody, Apiture.TransferItem {}
