/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { ApitureApi } from "@fern-api/apiture";

/**
 * Common fields of the transfer resource used to build other model schemas.
 */
export interface TransferFields {
    amount?: ApitureApi.MonetaryValue;
    sourceAccount?: ApitureApi.TransferAccountReference;
    targetAccount?: ApitureApi.TransferAccountReference;
    /** A customer-defined memo to describe the transfer. */
    memo?: string;
}
