/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { ApitureApi } from "@fern-api/apiture";

/**
 * Representation of a transfer resource.
 */
export interface Transfer extends ApitureApi.AbstractBody, ApitureApi.TransferItem {}
