/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { ApitureApi } from "@fern-api/apiture";

/**
 * Summary representation of a transfer resource in transfers collections. To fetch the full representation of this transfer, use the [`getTransfer`](#op-getTransfer) operation, passing this item's `id` field as the `transferId` path parameter.
 */
export interface TransferItem extends ApitureApi.TransferFields, ApitureApi.TimestampFields {
    /** The unique identifier for this transfer resource. This is an immutable opaque string. */
    id: ApitureApi.ReadOnlyResourceId;
    schedule: ApitureApi.TransferItemSchedule;
    /** The state of this transfer resource. */
    state: ApitureApi.TransferState;
    /** The date/time the transfer was processed. */
    processedAt?: string;
    /** The full name of the banking customer who last updated the transfer. */
    updatedBy?: string;
}
