/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The state of a transfer resource. <strong><code>transferState</code></strong> strings may have one of the following [enumerated values](https://dx.apiture.com/docs/api-documentation/concepts/label-groups#enumerations): <table> <tr>
 *   <th>Value</th><th>Description</th>
 * </tr> <tr>
 *     <td><strong><code>unscheduled</code></strong></td><td>Unscheduled: <p>A transfer which is not ready to be queued for processing</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>pendingApproval</code></strong></td><td>Pending Approval: <p>A transfer which is awaiting approval before it can be queued for processing</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>scheduled</code></strong></td><td>Scheduled: <p>A transfer which has been queued for processing</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>processing</code></strong></td><td>Processing: <p>A transfer which is being processed</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>processed</code></strong></td><td>Processed: <p>A transfer which has completed processing</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>failed</code></strong></td><td>Failed: <p>A transfer which has cannot be processed or failed while processing</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>other</code></strong></td><td>Other: <p>A transfer which is in some other state</p>
 * </td>
 *     </tr>
 * </table>
 *
 */
export type TransferState =
    | "unscheduled"
    | "pendingApproval"
    | "scheduled"
    | "processing"
    | "processed"
    | "failed"
    | "other";

export const TransferState = {
    Unscheduled: "unscheduled",
    PendingApproval: "pendingApproval",
    Scheduled: "scheduled",
    Processing: "processing",
    Processed: "processed",
    Failed: "failed",
    Other: "other",
} as const;
