/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Apiture } from "@fern-api/apiture";

/**
 * Common fields of the transfer resource used to build other model schemas.
 */
export interface TransferFields {
    amount?: Apiture.MonetaryValue;
    sourceAccount?: Apiture.TransferAccountReference;
    targetAccount?: Apiture.TransferAccountReference;
    /** A customer-defined memo to describe the transfer. */
    memo?: string;
}
