/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ApitureBanking from "../../../..";

export interface AccountsListAccountBalancesRequest {
    /**
     * The unique account identifiers of one or more internal accounts. (Internal accounts are those with `location` value of `internal`.) If omitted, this operation uses the accounts for which the customer has view permissions but is limited to at most 1000 accounts. Note: The account IDs are unrelated to the account number.
     */
    accounts?: ApitureBanking.ResourceId | ApitureBanking.ResourceId[];
    /**
     * When retrying the operation, pass the `retryCount` from the `incompleteAccountBalances` response.
     */
    retryCount?: number;
}
