/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { ApitureApi } from "@fern-api/apiture";

export interface ListAccountsRequest {
    /**
     * Include only accounts whose `product.type` is in pipe-delimited set. For example, to list only savings, checking, and CD accounts,  use <br>`?productType=savings|checking|cd`.
     */
    productType?: ApitureApi.ProductType | ApitureApi.ProductType[];
    /**
     * Filter accounts to just a subset of `internal` or `external` accounts (per the `location` property on the [`accountItem`](#schema-accountItem) schema).
     */
    location?: ApitureApi.AccountLocation;
    /**
     * The location of the next item in the collection. This is an opaque cursor supplied by the API service. Omit this to start at the beginning of the collection. The client does not define this value; the API services automatically pass the `?start=` parameter on the `nextPage_url`.
     */
    start?: string;
    /**
     * The maximum number of items to return in this paged response.
     */
    limit?: number;
    /**
     * Filter the result to accounts that have corresponding `true` values in `account.allows`. For example `?allows=transferTo,transferFrom,view` returns only accounts where `account.allows.transferTo`, `account.allows.transferFrom`, and `account.allows.view` are all `true` for the caller.
     */
    accountAllowsQueryParam?: string | string[];
}
