/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Apiture } from "@fern-api/apiture";

export interface ListAccountBalancesRequest {
    /**
     * 1000 maxItems is tied to 1000 maximum of the ?limit query parameter
     */
    accountIds?: Apiture.ResourceId | Apiture.ResourceId[];
    /**
     * When retrying the operation, pass the `retryCount` from the `incompleteAccountBalances` response.
     */
    retryCount?: number;
}
