/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ApitureApi } from "@fern-api/apiture";
import * as core from "../../../../core";

export const AchAccountRisk: core.serialization.Schema<serializers.AchAccountRisk.Raw, ApitureApi.AchAccountRisk> =
    core.serialization.enum_(["early", "normal", "float", "sameDay"]);

export declare namespace AchAccountRisk {
    type Raw = "early" | "normal" | "float" | "sameDay";
}
