/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ApitureApi } from "@fern-api/apiture";
import * as core from "../../../../core";

export const CutoffTime: core.serialization.ObjectSchema<serializers.CutoffTime.Raw, ApitureApi.CutoffTime> =
    core.serialization.object({
        type: core.serialization.lazy(async () => (await import("../../..")).CutoffTimeType),
        time: core.serialization.string(),
    });

export declare namespace CutoffTime {
    interface Raw {
        type: serializers.CutoffTimeType.Raw;
        time: string;
    }
}
