/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ApitureApi } from "@fern-api/apiture";
import * as core from "../../../../core";

export const InstitutionLocatorType: core.serialization.Schema<
    serializers.InstitutionLocatorType.Raw,
    ApitureApi.InstitutionLocatorType
> = core.serialization.enum_(["abaRoutingNumber", "swiftBicCode", "ibanAccountNumber"]);

export declare namespace InstitutionLocatorType {
    type Raw = "abaRoutingNumber" | "swiftBicCode" | "ibanAccountNumber";
}
