/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ApitureApi } from "@fern-api/apiture";
import * as core from "../../../../core";

export const InstitutionLookupResult: core.serialization.ObjectSchema<
    serializers.InstitutionLookupResult.Raw,
    ApitureApi.InstitutionLookupResult
> = core.serialization
    .object({
        found: core.serialization.boolean(),
        institution: core.serialization.lazyObject(async () => (await import("../../..")).SimpleInstitution).optional(),
        intermediaryInstitutions: core.serialization
            .list(core.serialization.lazyObject(async () => (await import("../../..")).SimpleInstitution))
            .optional(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).AbstractBody));

export declare namespace InstitutionLookupResult {
    interface Raw extends serializers.AbstractBody.Raw {
        found: boolean;
        institution?: serializers.SimpleInstitution.Raw | null;
        intermediaryInstitutions?: serializers.SimpleInstitution.Raw[] | null;
    }
}
