/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ApitureApi } from "@fern-api/apiture";
import * as core from "../../../../core";

export const TimeZoneId: core.serialization.Schema<serializers.TimeZoneId.Raw, ApitureApi.TimeZoneId> =
    core.serialization.string();

export declare namespace TimeZoneId {
    type Raw = string;
}
