/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Apiture } from "@fern-api/apiture";
import * as core from "../../../../core";

export const TransferScheduleDirection: core.serialization.Schema<
    serializers.TransferScheduleDirection.Raw,
    Apiture.TransferScheduleDirection
> = core.serialization.enum_(["debit", "credit", "both"]);

export declare namespace TransferScheduleDirection {
    type Raw = "debit" | "credit" | "both";
}
