/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Apiture } from "@fern-api/apiture";
import * as core from "../../../../core";

export const TransferScheduleItem: core.serialization.ObjectSchema<
    serializers.TransferScheduleItem.Raw,
    Apiture.TransferScheduleItem
> = core.serialization.object({
    scheduledOn: core.serialization.string(),
    effectiveOn: core.serialization.string(),
});

export declare namespace TransferScheduleItem {
    interface Raw {
        scheduledOn: string;
        effectiveOn: string;
    }
}
