/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ApitureBanking from "..";

/**
 * An array of account IDs.
 */
export type AccountIds = ApitureBanking.ResourceId[];
