/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Indicates where an account is held:
 *   * `internal` accounts at the current financial institution;
 *   * `external` accounts at another financial institution;
 *   * `outside` accounts non-banking accounts such as brokerage and fund accounts.
 * Account transfers are only allowed between `internal` and `external` accounts. All accounts are considered when calculating total cash balance.
 */
export type AccountLocation = "internal" | "external" | "outside";

export const AccountLocation = {
    Internal: "internal",
    External: "external",
    Outside: "outside",
} as const;
