/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ApitureBanking from "..";

/**
 * Fragment schema use to build other account schemas.
 */
export interface AccountFields {
    /** The unique identifier for this account resource. This is an immutable opaque string. */
    id: ApitureBanking.ReadOnlyResourceId;
    /** The human-readable label for this account. This is either the `nickname` (if assigned for the current customer), or the `product.label` concatenated with the `maskedNumber`. */
    label: string;
    nickname?: ApitureBanking.AccountNickname;
    maskedNumber: ApitureBanking.MaskedAccountNumber;
    product: ApitureBanking.ProductReference;
    /** Indicates where an account is held. */
    location: ApitureBanking.AccountLocation;
}
