/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AccountsListAccountsRequestLocation = "internal" | "external";

export const AccountsListAccountsRequestLocation = {
    Internal: "internal",
    External: "external",
} as const;
