/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Flags which indicate the permissions the current authorized user has on this account item resource. Most of these properties may only be `true` for internal accounts. These permissions are available in account items in the [`accounts`](#schema-accounts) list. See [`fullAccountPermissions`](#schema-fullAccountPermissions) for all capabilities a customer has on an account (the `account.allows` object in the [`account`](#schema-account) object response from [`getAccount`](#op-getAccount).)
 */
export interface AccountPermissions {
    /** If `true`, the customer may use this account for Bill Pay. */
    billPay: boolean;
    /** If `true`, the customer may use this account for mobile check deposits. */
    mobileCheckDeposit: boolean;
    /** If `true`, the customer may use this account as the target (deposit) account for account-to-account transfers. */
    transferFrom: boolean;
    /** If `true`, the customer may use this account as the source (debit) account for account-to-account transfers. */
    transferTo: boolean;
    /** If `true`, the customer may view the details of this account, including the account balance and transactions. */
    view: boolean;
    /** If `true`, the customer may view debit cards associated with this account. */
    viewCards: boolean;
    /** If true, the customer may manage debit cards associated with this account. This includes locking and unlocking cards, changing card controls, ordering cards, or canceling cards. */
    manageCards: boolean;
}
