/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ApitureBanking from "..";

/**
 * An account item in a list items in the `accounts` schema.
 */
export interface AccountItem {
    /** The unique identifier for this account resource. This is an immutable opaque string. */
    id?: ApitureBanking.ReadOnlyResourceId;
    /** The human-readable label for this account. This is either the `nickname` (if assigned for the current customer), or the `product.label` concatenated with the `maskedNumber`. */
    label?: string;
    nickname?: ApitureBanking.AccountNickname;
    maskedNumber?: ApitureBanking.MaskedAccountNumber;
    allows: ApitureBanking.AccountPermissions;
    product?: ApitureBanking.ProductReference;
    /** Indicates where an account is held. */
    location?: ApitureBanking.AccountLocation;
}
