/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ApitureBanking from "..";

export interface AccountJointOwners {
    /** An array containing account joint owner items. */
    items: ApitureBanking.AccountJointOwner[];
}
