/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Describes the risk level of a payment batch's settlement account.
 *
 * <strong><code>achAccountRisk</code></strong> strings may have one of the following
 * [enumerated values](https://dx.apiture.com/docs/api-documentation/concepts/label-groups#enumerations):
 *
 * <table>
 * <tr>
 *   <th>Value</th><th>Description</th>
 * </tr>
 *
 * <tr>
 *     <td><strong><code>early</code></strong></td><td>Early: <p>The account is debited three business days before the ACH transfer&#39;s effective date. The account balance is also checked for sufficient funds before the account is debited. A risk limit may apply for commercial accounts with an <code>early</code> risk level.</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>normal</code></strong></td><td>Normal: <p>The account is debited two business days before the ACH transfer&#39;s effective date. The account balance is also checked for sufficient funds before the account is debited. A risk limit may apply for commercial accounts with a <code>normal</code> risk level.</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>float</code></strong></td><td>Float: <p>The account is debited on the ACH transfer&#39;s effective date. The account balance is not checked for sufficient funds before the account is debited. A risk limit applies for commercial accounts with a <code>float</code> risk level.</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>sameDay</code></strong></td><td>Same Day: <p>The account is credited on the ACH transfer&#39;s effective day. The account balance is not checked because <code>sameDay</code> is used for credit. A risk limit and per-transaction limit applies.</p>
 * </td>
 *     </tr>
 * </table>
 *
 *
 */
export type AchAccountRisk = "early" | "normal" | "float" | "sameDay";

export const AchAccountRisk = {
    Early: "early",
    Normal: "normal",
    Float: "float",
    SameDay: "sameDay",
} as const;
