/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The ACH transfer type.
 *
 * <strong><code>achSecCode</code></strong> strings may have one of the following
 * [enumerated values](https://dx.apiture.com/docs/api-documentation/concepts/label-groups#enumerations):
 *
 * <table>
 * <tr>
 *   <th>Value</th><th>Description</th>
 * </tr>
 *
 * <tr>
 *     <td><strong><code>arc</code></strong></td><td>Accounts Receivable</td>
 *     </tr>
 * <tr>
 *     <td><strong><code>boc</code></strong></td><td>Back Office Conversion</td>
 *     </tr>
 * <tr>
 *     <td><strong><code>ccd</code></strong></td><td>Credit or Debit</td>
 *     </tr>
 * <tr>
 *     <td><strong><code>cie</code></strong></td><td>Customer-Initiated</td>
 *     </tr>
 * <tr>
 *     <td><strong><code>ctx</code></strong></td><td>Corporate Trade Exchange</td>
 *     </tr>
 * <tr>
 *     <td><strong><code>pop</code></strong></td><td>Point of Purchase</td>
 *     </tr>
 * <tr>
 *     <td><strong><code>ppd</code></strong></td><td>Prearranged Payment and Deposit</td>
 *     </tr>
 * <tr>
 *     <td><strong><code>rck</code></strong></td><td>Re-Presented Check</td>
 *     </tr>
 * <tr>
 *     <td><strong><code>tel</code></strong></td><td>Telephone-initiated</td>
 *     </tr>
 * <tr>
 *     <td><strong><code>web</code></strong></td><td>Internet-initiated/Mobile</td>
 *     </tr>
 * </table>
 *
 *
 */
export type AchSecCode = "arc" | "boc" | "ccd" | "cie" | "ctx" | "pop" | "ppd" | "rck" | "tel" | "web";

export const AchSecCode = {
    Arc: "arc",
    Boc: "boc",
    Ccd: "ccd",
    Cie: "cie",
    Ctx: "ctx",
    Pop: "pop",
    Ppd: "ppd",
    Rck: "rck",
    Tel: "tel",
    Web: "web",
} as const;
