/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ApitureBanking from "..";

/**
 * API problem or error, as per [RFC 7807 application/problem+json](https://tools.ietf.org/html/rfc7807).
 */
export interface ApiProblem {
    /**
     * A [URI reference (RFC3986)](https://tools.ietf.org/html/rfc3986) that identifies the problem type. If present, this is the URL of human-readable HTML documentation for the problem type. When this member is not present, its value is assumed to be `"about:blank"`.
     *
     */
    type?: string;
    /**
     * A short, human-readable summary of the problem type. The title is usually the same for all problem with the same `type`.
     *
     */
    title?: string;
    /**
     * The [HTTP status code](https://datatracker.ietf.org/doc/html/rfc7231#section-6) for this occurrence of the problem.
     *
     */
    status?: number;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     *
     */
    detail?: string;
    /**
     * A URI reference that identifies the specific occurrence of the problem. This is the URI of an API resource that the problem is related to, with a unique error correlation ID URI fragment
     *
     */
    instance?: string;
    id?: ApitureBanking.ReadOnlyResourceId;
    occurredAt?: ApitureBanking.ReadOnlyTimestamp;
    /** Optional root-causes if there are multiple problems in the request or API call processing. */
    problems?: ApitureBanking.ApiProblem[];
    /** Additional optional attributes related to the problem. This data conforms to the schema associated with the error type. */
    attributes?: Record<string, unknown>;
}
