/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ApitureBanking from "..";

/**
 * A single security question within the `questions` array of the [`challengeSecurityQuestions`](#schema-challengeSecurityQuestions)
 */
export interface ChallengeSecurityQuestion {
    id: ApitureBanking.ChallengePromptId;
    /** The text prompt of this security question. */
    prompt: string;
}
