/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The value of the identity `Challenge` request header that the client must send when retrying an operation which required a challenge.
 */
export type ChallengeToken = string;
