/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The unique ID of a prompt (such as a security question) in a challenge factor.
 */
export type ChallengePromptId = string;
