/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The name of challenge factor.
 *
 * <strong><code>challengeFactorType</code></strong> strings may have one of the following
 * [enumerated values](https://dx.apiture.com/docs/api-documentation/concepts/label-groups#enumerations):
 *
 * <table>
 * <tr>
 *   <th>Value</th><th>Description</th>
 * </tr>
 *
 * <tr>
 *     <td><strong><code>sms</code></strong></td><td>SMS: <p>One-time passcode sent to the primary mobile phone number</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>email</code></strong></td><td>Email: <p>One-time passcode sent to the primary email address</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>voice</code></strong></td><td>Voice: <p>One-time passcode communicated via automated voice phone call</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>authenticatorToken</code></strong></td><td>authenticator Token: <p>One-time passcode issued by a pre-registered hardware device, such as a token key fob, or an authenticator app</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>securityQuestions</code></strong></td><td>Security Questions: <p>Prompt with the user&#39;s security questions registered with their security profile</p>
 * </td>
 *     </tr>
 * </table>
 *
 *
 */
export type ChallengeFactorType = "sms" | "email" | "voice" | "securityQuestions" | "authenticatorToken";

export const ChallengeFactorType = {
    Sms: "sms",
    Email: "email",
    Voice: "voice",
    SecurityQuestions: "securityQuestions",
    AuthenticatorToken: "authenticatorToken",
} as const;
