/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ApitureBanking from "..";

/**
 * A numeric range for a checking account check number.
 */
export type CheckNumberRange = ApitureBanking.PositiveIntegerRange;
