/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ApitureBanking from "..";

/**
 * A representation of financial institution cutoff times for different money movement processes. A money movement process can have multiple cutoff times. The cutoff times are sorted in ascending chronological order by money movement process.
 */
export interface CutoffTimes extends ApitureBanking.AbstractBody {
    timeZoneId: ApitureBanking.TimeZoneId;
    /** A list of cutoff times for a financial institution. */
    items: ApitureBanking.CutoffTime[];
}
