/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ApitureBanking from "..";

/**
 * A representation of a cutoff time for a money movement process at a financial institution.
 */
export interface CutoffTime {
    type: ApitureBanking.CutoffTimeType;
    /** The cutoff time for a product formatted in [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339) `time` format: `hh:mm`. The time is expressed in 24 hour time and is set to the local time zone of the financial institution. */
    time: string;
}
