/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A page of zero or more accounts that are eligible to be assigned as an overdraft protection account for another account.
 */
export interface EligibleOverdraftAccounts {
    items?: unknown;
    /** The maximum number of overdraft protection accounts that may be linked to the account. */
    maximumOverdraftAccounts: number;
    /** The URL of the next page of eligible accounts. If this URL is omitted, there are no more accounts. */
    nextPageUrl?: string;
    /** The opaque cursor that specifies the starting location of this page of items. */
    start?: string;
    /** The number of items requested for this page response. The length of the `items` array may be less that `limit`. */
    limit: number;
}
