/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ApitureBanking from "..";

/**
 * An account that is eligible to be assigned as an overdraft protection account for another account.
 */
export type EligibleOverdraftAccountItem = ApitureBanking.OverdraftAccountFields;
