/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ApitureBanking from "..";

/**
 * Flags which indicate the permissions the current authorized user has on this account resource. Most of these properties may only be `true` for internal accounts. These permissions are available in [`account`](#schema-account) response from the [`getAccount`](#op-getAccount) operation. See [`accountPermissions`](#schema-accountPermissions) for the subset of permission in `account.allows` flags in the [`listAccounts`](#op-listAccounts) response.
 */
export interface FullAccountPermissions extends ApitureBanking.AccountPermissions {
    /** If `true`, the customer can list the other joint owners on the account and invite new joint owners. */
    manageJointOwners: boolean;
    /** If `true`, the customer can list and manage overdraft account settings. */
    manageOverdraftAccounts: boolean;
}
