/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A full account number. This is the number that the customer uses to reference the account within the financial institution.
 */
export type FullAccountNumber = string;
