/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ApitureBanking from "..";

/**
 * An array of account balances by account ID, some of which are incomplete. Use the values in `incompleteAccounts` and `retryCount` to retry the [`listAccountBalances`](#op-listAccountBalances) operation.
 */
export interface IncompleteAccountBalances extends ApitureBanking.AbstractBody {
    /** An array of items, one for each of the `?accounts=` in the request, returned in the same order. */
    items: ApitureBanking.AccountBalance[];
    incompleteAccounts: ApitureBanking.AccountIds;
    /** Pass this value as the as the `?retryCount=` parameter with the next retry of the [`listAccountBalances`](#op-listAccountBalances) operation. */
    retryCount: number;
}
