/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ApitureBanking from "..";

/**
 * Response when requesting transactions that are not yet available.
 */
export interface IncompleteTransactions extends ApitureBanking.AbstractBody {
    /** Pass this value as the as the `?retryCount=` parameter with the next retry of the [`listTransactions`](#op-listTransactions) operation. */
    retryCount: number;
}
