/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ApitureBanking from "..";

/**
 * A joint owner invitation.
 */
export interface JointOwnerInvitation extends ApitureBanking.AbstractBody, ApitureBanking.JointOwnerInvitationFields {
    id: ApitureBanking.ReadOnlyResourceId;
}
