/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A masked account number: an asterisk `*` followed by one to four characters of the `fullAccountNumber`.
 */
export type MaskedAccountNumber = string;
