/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ApitureBanking from "..";

/**
 * Fields of an overdraft protection account, used to compose other schemas.
 */
export interface OverdraftAccountFields {
    id?: ApitureBanking.ResourceId;
    /** The human-readable label for this account. This is either the `nickname` (if assigned for the current customer), or the `product.label` concatenated with the `maskedNumber`. */
    label?: string;
    maskedNumber?: ApitureBanking.MaskedAccountNumber;
}
