/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Fields used to compose other overdraft protection schemas.
 */
export interface OverdraftProtectionFields {
    accounts?: unknown;
}
