/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A positive integer range, supporting inclusive or exclusive endpoints. The value may have the following forms: <ul> <li>`1200` match the integer 1,200 exactly</li> <li>`[1000,1200)` matches items where `1000 <= number < 1200`</li> <li>`[1000,1199]` matches items where`1000 <= number <= 1199`</li> <li>`[999,1200]` matches items where `999 < number < 1200`</li> <li>`[1200,]`  `number >= 1200`</li> <li>`(1200,)` greater than the value: `number >= 1200`</li> <li>`[,1200]` less than or equal to the value: `number <= 1200`</li> <li>`(,1200)` less than the value: `number < 1200`</li> </ul>
 */
export type PositiveIntegerRange = string;
