/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ApitureBanking from "..";

/**
 * API problem or error response, as per [RFC 7807 application/problem+json](https://tools.ietf.org/html/rfc7807).
 */
export interface ProblemResponse extends ApitureBanking.AbstractBody, ApitureBanking.ApiProblem {}
