/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A readonly or derived timestamp (an instant in time) formatted in [RFC 3339](https://tools.ietf.org/html/rfc3339) `date-time` UTC format: `YYYY-MM-DDThh:mm:ss.sssZ`.<br>The schema `readOnlyTimestamp` was added on version `0.4.0` of the API.
 */
export type ReadOnlyTimestamp = string;
