/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The unique, opaque system identifier for a resource. This case-sensitive ID is also used as path parameters in URLs or in other properties or parameters that reference a resource by ID rather than URL.
 */
export type ResourceId = string;
