/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ApitureBanking from "..";

/**
 * Summary representation of a transaction resource in transactions collections.
 */
export interface TransactionItem extends ApitureBanking.AbstractBody, ApitureBanking.TransactionFields {}
