/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ApitureBanking from "..";

/**
 * The transaction categorization.
 */
export interface TransactionCategorization {
    label: ApitureBanking.TransactionCategoryLabel;
    /** The unique ID of this transaction's category. */
    id: string;
}
