/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ApitureBanking from "..";

export interface TransactionCategories {
    /** An array containing transaction category items. */
    items: ApitureBanking.TransactionCategory[];
}
