/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * If the type is `debit` or `credit`, the subtype conveys further transaction type details.
 *
 * <strong><code>transactionSubType</code></strong> strings may have one of the following
 * [enumerated values](https://dx.apiture.com/docs/api-documentation/concepts/label-groups#enumerations):
 *
 * <table>
 * <tr>
 *   <th>Value</th><th>Description</th>
 * </tr>
 *
 * <tr>
 *     <td><strong><code>check</code></strong></td><td>Check: <p>A check drawn from a checking account.</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>other</code></strong></td><td>Other: <p>Some other transaction type.</p>
 * </td>
 *     </tr>
 * </table>
 *
 *
 */
export type TransactionSubType = "check" | "other";

export const TransactionSubType = {
    Check: "check",
    Other: "other",
} as const;
