/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Describes a check associated with a transaction for a checking account. This object is only present if the transaction `type` is `debit` and the `subtype` is `check`.
 */
export interface TransactionCheck {
    /** The check number. */
    number: number;
    /** The URL for downloading the image of the front of the check. */
    imageFrontUrl?: string;
    /** The URL for downloading the image of the front of the check. */
    imageBackUrl?: string;
}
