/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ApitureBanking from "..";

/**
 * Collection of transfers. The items in the collection are ordered in the `items` array. The response object may contain the `nextPage_url` pagination link..
 */
export interface Transfers extends ApitureBanking.AbstractPagedBody {
    /** An array containing a page of transfer items. */
    items: ApitureBanking.TransferItem[];
    /** The number of transfers that meet the filters in the `listTransfers` operation. This is optional and only included if the service can calculate it efficiently. */
    count?: number;
}
