/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ApitureBanking from "..";

/**
 * Representation of transaction category resources.
 */
export interface TransactionCategory extends ApitureBanking.AbstractBody, ApitureBanking.TransactionCategorization {
    type: ApitureBanking.TransactionCategoryType;
}
