/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Distinguishes between balance, debit, or credit transactions.
 *
 * <strong><code>transactionType</code></strong> strings may have one of the following
 * [enumerated values](https://dx.apiture.com/docs/api-documentation/concepts/label-groups#enumerations):
 *
 * <table>
 * <tr>
 *   <th>Value</th><th>Description</th>
 * </tr>
 *
 * <tr>
 *     <td><strong><code>balance</code></strong></td><td>Balance: <p>A pseudo-transaction that conveys the account balance.</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>debit</code></strong></td><td>Debit: <p>A debit against the account.</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>credit</code></strong></td><td>Credit: <p>A credit transaction.</p>
 * </td>
 *     </tr>
 * </table>
 *
 *
 */
export type TransactionType = "balance" | "debit" | "credit";

export const TransactionType = {
    Balance: "balance",
    Debit: "debit",
    Credit: "credit",
} as const;
