/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Indicates why a transfer date is restricted.
 *
 * <strong><code>transferDateRestrictionType</code></strong> strings may have one of the following
 * [enumerated values](https://dx.apiture.com/docs/api-documentation/concepts/label-groups#enumerations):
 *
 * <table>
 * <tr>
 *   <th>Value</th><th>Description</th>
 * </tr>
 *
 * <tr>
 *     <td><strong><code>pastDate</code></strong></td><td>Past Date: <p>The transfer date is in the past</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>pastCutoffTime</code></strong></td><td>Past Cutoff Time: <p>Transfers disallowed because the current time is past the financial institutions&#39; cutoff time</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>riskRestricted</code></strong></td><td>Risk Restricted: <p>The date is restricted because the risk level requires one or more days for a debit to clear</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>holiday</code></strong></td><td>Holiday: <p>A <a href="https://www.federalreserve.gov/aboutthefed/k8.htm">Federal Reserve System observed holiday</a></p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>closure</code></strong></td><td>Closure: <p>Financial institution closure, such as a weekend or other planned closure</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>other</code></strong></td><td>Other: <p>Other</p>
 * </td>
 *     </tr>
 * </table>
 *
 *
 */
export type TransferDateRestrictionType =
    | "pastDate"
    | "pastCutoffTime"
    | "riskRestricted"
    | "holiday"
    | "closure"
    | "other";

export const TransferDateRestrictionType = {
    PastDate: "pastDate",
    PastCutoffTime: "pastCutoffTime",
    RiskRestricted: "riskRestricted",
    Holiday: "holiday",
    Closure: "closure",
    Other: "other",
} as const;
