/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ApitureBanking from "..";

/**
 * Representation of a transfer resource.
 */
export interface Transfer extends ApitureBanking.AbstractBody, ApitureBanking.TransferItem {}
