/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ApitureBanking from "..";

/**
 * Common fields of the transfer resource used to build other model schemas.
 */
export interface TransferFields {
    amount?: ApitureBanking.MonetaryValue;
    sourceAccount?: ApitureBanking.TransferAccountReference;
    targetAccount?: ApitureBanking.TransferAccountReference;
    /** A customer-defined memo to describe the transfer. */
    memo?: string;
}
