/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ApitureBanking from "..";

/**
 * A representation of a financial institution used for wire transfers.
 */
export interface WireTransferInstitution extends ApitureBanking.SimpleInstitution {
    /** The clearing code used to identify the financial institution for select countries. */
    localClearingCode?: string;
}
