/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Apiture } from "@fern-api/apiture";
import * as core from "../../../../core";

export const CheckNumberRange: core.serialization.Schema<serializers.CheckNumberRange.Raw, Apiture.CheckNumberRange> =
    core.serialization.lazy(async () => (await import("../../..")).PositiveIntegerRange);

export declare namespace CheckNumberRange {
    type Raw = serializers.PositiveIntegerRange.Raw;
}
