/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ApitureApi } from "@fern-api/apiture";
import * as core from "../../../../core";

export const CheckNumberRange: core.serialization.Schema<
    serializers.CheckNumberRange.Raw,
    ApitureApi.CheckNumberRange
> = core.serialization.lazy(async () => (await import("../../..")).PositiveIntegerRange);

export declare namespace CheckNumberRange {
    type Raw = serializers.PositiveIntegerRange.Raw;
}
