/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ApitureApi } from "@fern-api/apiture";
import * as core from "../../../../core";

export const TransactionCategoryLabel: core.serialization.Schema<
    serializers.TransactionCategoryLabel.Raw,
    ApitureApi.TransactionCategoryLabel
> = core.serialization.string();

export declare namespace TransactionCategoryLabel {
    type Raw = string;
}
