/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ApitureApi } from "@fern-api/apiture";
import * as core from "../../../../core";

export const Transactions: core.serialization.ObjectSchema<serializers.Transactions.Raw, ApitureApi.Transactions> =
    core.serialization
        .object({
            items: core.serialization
                .list(core.serialization.lazyObject(async () => (await import("../../..")).TransactionItem))
                .optional(),
            count: core.serialization.number().optional(),
        })
        .extend(core.serialization.lazyObject(async () => (await import("../../..")).AbstractPagedBody));

export declare namespace Transactions {
    interface Raw extends serializers.AbstractPagedBody.Raw {
        items?: serializers.TransactionItem.Raw[] | null;
        count?: number | null;
    }
}
