/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Apiture } from "@fern-api/apiture";
import * as core from "../../../../core";

export const TransactionSubType: core.serialization.Schema<
    serializers.TransactionSubType.Raw,
    Apiture.TransactionSubType
> = core.serialization.enum_(["check", "other"]);

export declare namespace TransactionSubType {
    type Raw = "check" | "other";
}
