/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ApitureApi } from "@fern-api/apiture";
import * as core from "../../../../core";

export const TransactionMerchant: core.serialization.ObjectSchema<
    serializers.TransactionMerchant.Raw,
    ApitureApi.TransactionMerchant
> = core.serialization.object({
    name: core.serialization.string().optional(),
    websiteUrl: core.serialization.property("website_url", core.serialization.string().optional()),
    logoUrl: core.serialization.property("logo_url", core.serialization.string().optional()),
});

export declare namespace TransactionMerchant {
    interface Raw {
        name?: string | null;
        website_url?: string | null;
        logo_url?: string | null;
    }
}
