/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ApitureApi } from "@fern-api/apiture";
import * as core from "../../../../core";

export const TransactionCheck: core.serialization.ObjectSchema<
    serializers.TransactionCheck.Raw,
    ApitureApi.TransactionCheck
> = core.serialization.object({
    number: core.serialization.number(),
    imageFrontUrl: core.serialization.property("imageFront_url", core.serialization.string().optional()),
    imageBackUrl: core.serialization.property("imageBack_url", core.serialization.string().optional()),
});

export declare namespace TransactionCheck {
    interface Raw {
        number: number;
        imageFront_url?: string | null;
        imageBack_url?: string | null;
    }
}
