/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ApitureApi } from "@fern-api/apiture";
import * as core from "../../../../core";

export const TransactionCategorization: core.serialization.ObjectSchema<
    serializers.TransactionCategorization.Raw,
    ApitureApi.TransactionCategorization
> = core.serialization.object({
    label: core.serialization.lazy(async () => (await import("../../..")).TransactionCategoryLabel),
    id: core.serialization.string(),
});

export declare namespace TransactionCategorization {
    interface Raw {
        label: serializers.TransactionCategoryLabel.Raw;
        id: string;
    }
}
