/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Properties of a simple address, used to compose other addresses.
 */
export interface AddressFields {
    /** The first line of the postal address. In the US, this typically includes the building number and street name. */
    address1: string;
    /** The second line of the street address. This should only be used if it has a value. Typical values include building numbers, suite numbers, and other identifying information beyond the first line of the postal address. */
    address2?: string;
    /** The city/town/municipality of the address. */
    locality: string;
    /** The [ISO-3611 alpha-2](https://www.iso.org/glossary-for-iso-3166.html) value for the country associated with the postal address. */
    countryCode: string;
}
