/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { ApitureApi } from "@fern-api/apiture";

/**
 * A simple representation of a financial institution.
 */
export interface SimpleInstitution {
    /** The financial institution's name. */
    name: string;
    address: ApitureApi.Address;
    /** The [American Bankers Association routing number](https://www.aba.com/about-us/routingnumber), [SWIFT Business Identifier Code (BIC) code](https://www.swift.com/standards/data-standards/bic-business-identifier-code), or [IBAN account number](https://www.ecbs.org/iban.htm) of the institution. The form of this institution locator string is set with the `locatorType` property. */
    locator: string;
    locatorType: ApitureApi.InstitutionLocatorType;
}
