/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Summary representation of a transfer schedule resource in transfer schedule list.
 */
export interface TransferScheduleItem {
    /** The scheduled date of the calculated calendar recurrence in `YYYY-MM-DD` [RFC 3339](https://tools.ietf.org/html/rfc3339) date format. */
    scheduledOn: string;
    /** The effective date of the recurrence in `YYYY-MM-DD` [RFC 3339](https://tools.ietf.org/html/rfc3339) date format. When the effective date differs from the scheduled date, it is due to a banking holiday, weekend, or other non-business day. The date is adjusted to before the scheduled date when the transfer direction is `credit` and adjusted to after the scheduled date when the transfer direction is `debit`. */
    effectiveOn: string;
}
