/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Provides the direction in which a transfer flows. <strong><code>transferScheduleDirection</code></strong> strings may have one of the following [enumerated values](https://dx.apiture.com/docs/api-documentation/concepts/label-groups#enumerations): <table> <tr>
 *   <th>Value</th><th>Description</th>
 * </tr> <tr>
 *     <td><strong><code>debit</code></strong></td><td>Debit: <p>Money is transferred from a payer to the financial institution</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>credit</code></strong></td><td>Credit: <p>Money is transferred from the financial institution to a payee</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>both</code></strong></td><td>Both: <p>Money is transferred both to and from a payee/payer</p>
 * </td>
 *     </tr>
 * </table>
 *
 */
export type TransferScheduleDirection = "debit" | "credit" | "both";

export const TransferScheduleDirection = {
    Debit: "debit",
    Credit: "credit",
    Both: "both",
} as const;
