/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Apiture } from "@fern-api/apiture";

/**
 * List of transfer methods. The items in the list are ordered in the `items` array.
 */
export interface TransferSchedules extends Apiture.AbstractBody {
    /** An array containing upcoming transfer schedule items. */
    items: Apiture.TransferScheduleItem[];
}
