/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Apiture } from "@fern-api/apiture";

/**
 * A date where a transfer restriction occurs, and the `reason` it is restricted. If the `reason` is `holiday`, `closure` and the transfer is an ACH transfer, the object also contains either a `debitOn` or `creditOn` date or both.
 */
export interface TransferDateRestriction {
    /** The date that a transfers restriction occurs, is in the [ISO 8601 Date](https://en.wikipedia.org/wiki/ISO_8601#Calendar_dates) format, `yyyy-mm-dd`. */
    occursOn: string;
    reason: Apiture.TransferDateRestrictionType;
    /** The date the local financial institution account is credited in [RFC 3339 `YYYY-MM-DD`](https://tools.ietf.org/html/rfc3339) date format. This is derived from the `date` based on the `risk` level. The credit-on date normally falls one business day after the restricted `date`. This property is only returned if the payment `type` is `achDebit` or `ach`. */
    creditOn?: string;
    /** The date the local financial institution account is debited in [RFC 3339 `YYYY-MM-DD`](https://tools.ietf.org/html/rfc3339) date format. This is derived from the `date` based on the `risk` level and the transfer direction (`achDebit` or `achCredit`). The debit-on date normally falls one to three business days before the restricted `date`. This property is only returned if the payment `type` is `achCredit` or `ach`. */
    debitOn?: string;
}
