/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as ApitureBanking from "../../..";
import URLSearchParams from "@ungap/url-search-params";
import * as serializers from "../../../../serialization";
import urlJoin from "url-join";
import * as errors from "../../../../errors";

export declare namespace Transactions {
    interface Options {
        environment?: environments.ApitureBankingEnvironment | string;
        apiKey: core.Supplier<string>;
    }
}

export class Transactions {
    constructor(protected readonly options: Transactions.Options) {}

    /**
     * Return a [paginated](https://dx.apiture.com/docs/api-documentation/concepts/pagination) collection of transaction history for this internal account. The [`nextPage_url`](https://dx.apiture.com/docs/api-documentation/concepts/links) link in the response, if present, is a pagination link to the next page of transactions for the given filters.
     *
     * This operation returns a 403 Forbidden error if the customer does not have `view` permissions in the `account.allows` object, or a 422 Unprocessable Entity if called on an external account.
     *
     * The default response lists only recent transactions. Normally, this is transactions for the most recent 30 days, although for high-volume accounts, it may be a shorter period.
     * @throws {@link ApitureBanking.BadRequestError}
     * @throws {@link ApitureBanking.UnauthorizedError}
     * @throws {@link ApitureBanking.ForbiddenError}
     * @throws {@link ApitureBanking.NotFoundError}
     * @throws {@link ApitureBanking.UnprocessableEntityError}
     * @throws {@link ApitureBanking.TooManyRequestsError}
     */
    public async listTransactions(
        accountId: ApitureBanking.ResourceId,
        request: ApitureBanking.TransactionsListTransactionsRequest = {}
    ): Promise<ApitureBanking.Transactions> {
        const {
            start,
            limit,
            occurredOn,
            posted,
            createdOn,
            postedOn,
            category,
            type: type_,
            subtype,
            amount,
            checkNumber,
            retryCount,
        } = request;
        const _queryParams = new URLSearchParams();
        if (start != null) {
            _queryParams.append("start", start);
        }

        if (limit != null) {
            _queryParams.append("limit", limit.toString());
        }

        if (occurredOn != null) {
            _queryParams.append("occurredOn", occurredOn);
        }

        if (posted != null) {
            _queryParams.append("posted", posted.toString());
        }

        if (createdOn != null) {
            _queryParams.append("createdOn", createdOn);
        }

        if (postedOn != null) {
            _queryParams.append("postedOn", postedOn);
        }

        if (category != null) {
            if (Array.isArray(category)) {
                for (const _item of category) {
                    _queryParams.append("category", _item);
                }
            } else {
                _queryParams.append("category", category);
            }
        }

        if (type_ != null) {
            if (Array.isArray(type_)) {
                for (const _item of type_) {
                    _queryParams.append("type", _item);
                }
            } else {
                _queryParams.append("type", type_);
            }
        }

        if (subtype != null) {
            if (Array.isArray(subtype)) {
                for (const _item of subtype) {
                    _queryParams.append("subtype", _item);
                }
            } else {
                _queryParams.append("subtype", subtype);
            }
        }

        if (amount != null) {
            _queryParams.append("amount", amount);
        }

        if (checkNumber != null) {
            _queryParams.append("checkNumber", checkNumber);
        }

        if (retryCount != null) {
            _queryParams.append("retryCount", retryCount.toString());
        }

        const _response = await core.fetcher({
            url: urlJoin(
                this.options.environment ?? environments.ApitureBankingEnvironment.Default,
                `accounts/${await serializers.ResourceId.jsonOrThrow(accountId)}/transactions`
            ),
            method: "GET",
            headers: {
                "API-Key": await core.Supplier.get(this.options.apiKey),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@fern-api/apiture",
                "X-Fern-SDK-Version": "0.0.6",
            },
            contentType: "application/json",
            queryParameters: _queryParams,
            timeoutMs: 60000,
        });
        if (_response.ok) {
            return await serializers.Transactions.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new ApitureBanking.BadRequestError(
                        await serializers.ProblemResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        })
                    );
                case 401:
                    throw new ApitureBanking.UnauthorizedError(
                        await serializers.ProblemResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        })
                    );
                case 403:
                    throw new ApitureBanking.ForbiddenError(
                        await serializers.ProblemResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        })
                    );
                case 404:
                    throw new ApitureBanking.NotFoundError(
                        await serializers.ProblemResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        })
                    );
                case 422:
                    throw new ApitureBanking.UnprocessableEntityError(
                        await serializers.ProblemResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        })
                    );
                case 429:
                    throw new ApitureBanking.TooManyRequestsError(
                        await serializers.ProblemResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        })
                    );
                default:
                    throw new errors.ApitureBankingError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApitureBankingError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.ApitureBankingTimeoutError();
            case "unknown":
                throw new errors.ApitureBankingError({
                    message: _response.error.errorMessage,
                });
        }
    }
}
