/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Apiture } from "@fern-api/apiture";

/**
 * Representation of account joint owner resources.
 */
export interface AccountJointOwner extends Apiture.AbstractBody {
    id: Apiture.ReadOnlyResourceId;
    /** The full name of the joint owner. */
    name: string;
}
