/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Apiture } from "@fern-api/apiture";

/**
 * An array of account IDs.
 */
export type AccountIds = Apiture.ResourceId[];
