/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { ApitureApi } from "@fern-api/apiture";

/**
 * An array of account IDs.
 */
export type AccountIds = ApitureApi.ResourceId[];
