/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Apiture } from "@fern-api/apiture";

/**
 * A paginated list of the customer's accounts. This list contains internal banking accounts and external banking accounts. and outside fund accounts. The `location` property indicates where the account is held. Items in the list contain `url` links to the actual account resource which are in the `accounts`, `externalAccounts` or `outsideAccounts` collections.
 */
export interface Accounts extends Apiture.AbstractPagedBody {
    /** The array of items in this page of accounts. This array may be empty. */
    items: Apiture.AccountItem[];
    /** The total number of accounts for which the user has access. This value ignores any filters. This value is _optional_ and may be omitted if the count is not computable efficiently. */
    count?: number;
    primaryAccountId?: Apiture.ReadOnlyResourceId;
}
