/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { ApitureApi } from "@fern-api/apiture";

/**
 * An account item in a list items in the `accounts` schema.
 */
export interface AccountItem {
    /** The unique identifier for this account resource. This is an immutable opaque string. */
    id?: ApitureApi.ReadOnlyResourceId;
    /** The human-readable label for this account. This is either the `nickname` (if assigned for the current customer), or the `product.label` concatenated with the `maskedNumber`. */
    label?: string;
    nickname?: ApitureApi.AccountNickname;
    maskedNumber?: ApitureApi.MaskedAccountNumber;
    allows: ApitureApi.AccountPermissions;
    product?: ApitureApi.ProductReference;
    /** Indicates where an account is held. */
    location?: ApitureApi.AccountLocation;
}
