/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { ApitureApi } from "@fern-api/apiture";

/**
 * Collection of account joint owners. The items in the collection are ordered in the `items` array.
 */
export interface AccountJointOwners {
    /** An array containing account joint owner items. */
    items: ApitureApi.AccountJointOwner[];
}
