/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { ApitureApi } from "@fern-api/apiture";

/**
 * An internal customer account.
 */
export interface Account extends ApitureApi.AbstractBody, ApitureApi.AccountFields {
    /** Flags which indicate the permissions the current authorized user has on this account resource. */
    allows: ApitureApi.FullAccountPermissions;
    /** If `true`, the customer has opted in to receive account statements electronically. */
    electronicStatements: boolean;
}
