/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Fields used to compose other joint owner invitation schemas.
 */
export interface JointOwnerInvitationFields {
    /** The invitee's first name. */
    firstName: string;
    /** The invitee's last name name. */
    lastName: string;
    /** The last 4 digits of the invitee's tax ID number (Social Security Number). This is not sent in the invitation email, but if the invitee enrolls in digital banking, this identification must match the last four digits of the tax ID they use to enroll. */
    taxId?: string;
    /** A string shared by the inviter with the invitee to verify their identity. This is not sent in the invitation. The inviter should share this string with the invitee though another channel. */
    sharedSecret: string;
    /** The invitee's email address. */
    emailAddress: string;
    /** If `true`, the invitee is not allowed to order or manage debit cards for the account. */
    disallowDebitCardAccess?: boolean;
}
