/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Apiture } from "@fern-api/apiture";

/**
 * A request to create an invitation to add a new joint owner to an account.
 */
export interface NewJointOwnerInvitation extends Apiture.AbstractBody, Apiture.JointOwnerInvitationFields {}
