/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { ApitureApi } from "@fern-api/apiture";

/**
 * A request to create an invitation to add a new joint owner to an account.
 */
export interface NewJointOwnerInvitation extends ApitureApi.AbstractBody, ApitureApi.JointOwnerInvitationFields {}
