/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { ApitureApi } from "@fern-api/apiture";

/**
 * Representation of the overdraft protection settings, consisting of a list of overdraft protection accounts linked to the account identified by the `{accountId}`.
 */
export interface OverdraftProtection extends ApitureApi.AbstractBody, ApitureApi.OverdraftProtectionFields {
    /** The maximum number of overdraft protection accounts that may be linked to the account. */
    maximumOverdraftAccounts: number;
}
