/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { ApitureApi } from "@fern-api/apiture";

/**
 * Representation of request used to patch the overdraft protection settings consisting of a list of overdraft protection accounts linked to the account identified by the `{accountId}`.
 */
export interface OverdraftProtectionPatch extends ApitureApi.AbstractBody, ApitureApi.OverdraftProtectionFields {}
