/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Fields used to compose other overdraft protection schemas.
 */
export interface OverdraftProtectionFields {
    /** The ordered list of accounts assigned as overdraft protection accounts. This array is limited to no more than `maximumOverdraftAccounts` accounts. */
    accounts?: unknown;
}
