/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const AccountRoutingNumber: core.serialization.Schema<
    serializers.AccountRoutingNumber.Raw,
    ApitureBanking.AccountRoutingNumber
> = core.serialization.string();

export declare namespace AccountRoutingNumber {
    type Raw = string;
}
