/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const AccountIds: core.serialization.Schema<serializers.AccountIds.Raw, ApitureBanking.AccountIds> =
    core.serialization.list(core.serialization.lazy(async () => (await import("..")).ResourceId));

export declare namespace AccountIds {
    type Raw = serializers.ResourceId.Raw[];
}
