/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const AccountsListAccountsRequestLocation: core.serialization.Schema<
    serializers.AccountsListAccountsRequestLocation.Raw,
    ApitureBanking.AccountsListAccountsRequestLocation
> = core.serialization.enum_(["internal", "external"]);

export declare namespace AccountsListAccountsRequestLocation {
    type Raw = "internal" | "external";
}
