/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const Account: core.serialization.ObjectSchema<serializers.Account.Raw, ApitureBanking.Account> =
    core.serialization
        .object({
            allows: core.serialization.lazyObject(async () => (await import("..")).FullAccountPermissions),
            electronicStatements: core.serialization.boolean(),
        })
        .extend(core.serialization.lazyObject(async () => (await import("..")).AbstractBody))
        .extend(core.serialization.lazyObject(async () => (await import("..")).AccountFields));

export declare namespace Account {
    interface Raw extends serializers.AbstractBody.Raw, serializers.AccountFields.Raw {
        allows: serializers.FullAccountPermissions.Raw;
        electronicStatements: boolean;
    }
}
