/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const AddressFields: core.serialization.ObjectSchema<
    serializers.AddressFields.Raw,
    ApitureBanking.AddressFields
> = core.serialization.object({
    address1: core.serialization.string(),
    address2: core.serialization.string().optional(),
    locality: core.serialization.string(),
    countryCode: core.serialization.string(),
});

export declare namespace AddressFields {
    interface Raw {
        address1: string;
        address2?: string | null;
        locality: string;
        countryCode: string;
    }
}
