/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const ChallengeFactorType: core.serialization.Schema<
    serializers.ChallengeFactorType.Raw,
    ApitureBanking.ChallengeFactorType
> = core.serialization.enum_(["sms", "email", "voice", "securityQuestions", "authenticatorToken"]);

export declare namespace ChallengeFactorType {
    type Raw = "sms" | "email" | "voice" | "securityQuestions" | "authenticatorToken";
}
