/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const ChallengePromptId: core.serialization.Schema<
    serializers.ChallengePromptId.Raw,
    ApitureBanking.ChallengePromptId
> = core.serialization.string();

export declare namespace ChallengePromptId {
    type Raw = string;
}
