/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const ChallengeSecurityQuestion: core.serialization.ObjectSchema<
    serializers.ChallengeSecurityQuestion.Raw,
    ApitureBanking.ChallengeSecurityQuestion
> = core.serialization.object({
    id: core.serialization.lazy(async () => (await import("..")).ChallengePromptId),
    prompt: core.serialization.string(),
});

export declare namespace ChallengeSecurityQuestion {
    interface Raw {
        id: serializers.ChallengePromptId.Raw;
        prompt: string;
    }
}
