/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const ChallengeSecurityQuestions: core.serialization.ObjectSchema<
    serializers.ChallengeSecurityQuestions.Raw,
    ApitureBanking.ChallengeSecurityQuestions
> = core.serialization.object({
    questions: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("..")).ChallengeSecurityQuestion)
    ),
});

export declare namespace ChallengeSecurityQuestions {
    interface Raw {
        questions: serializers.ChallengeSecurityQuestion.Raw[];
    }
}
