/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const CheckNumberRange: core.serialization.Schema<
    serializers.CheckNumberRange.Raw,
    ApitureBanking.CheckNumberRange
> = core.serialization.lazy(async () => (await import("..")).PositiveIntegerRange);

export declare namespace CheckNumberRange {
    type Raw = serializers.PositiveIntegerRange.Raw;
}
