/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const CutoffTimeType: core.serialization.Schema<serializers.CutoffTimeType.Raw, ApitureBanking.CutoffTimeType> =
    core.serialization.enum_([
        "ach",
        "sameDayAch",
        "domesticWireTransfer",
        "internationalWireTransfer",
        "internalTransfer",
        "externalTransfer",
        "billPay",
    ]);

export declare namespace CutoffTimeType {
    type Raw =
        | "ach"
        | "sameDayAch"
        | "domesticWireTransfer"
        | "internationalWireTransfer"
        | "internalTransfer"
        | "externalTransfer"
        | "billPay";
}
