/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const CutoffTimes: core.serialization.ObjectSchema<serializers.CutoffTimes.Raw, ApitureBanking.CutoffTimes> =
    core.serialization
        .object({
            timeZoneId: core.serialization.lazy(async () => (await import("..")).TimeZoneId),
            items: core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).CutoffTime)),
        })
        .extend(core.serialization.lazyObject(async () => (await import("..")).AbstractBody));

export declare namespace CutoffTimes {
    interface Raw extends serializers.AbstractBody.Raw {
        timeZoneId: serializers.TimeZoneId.Raw;
        items: serializers.CutoffTime.Raw[];
    }
}
