/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const DateRange: core.serialization.Schema<serializers.DateRange.Raw, ApitureBanking.DateRange> =
    core.serialization.string();

export declare namespace DateRange {
    type Raw = string;
}
