/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const EligibleOverdraftAccounts: core.serialization.ObjectSchema<
    serializers.EligibleOverdraftAccounts.Raw,
    ApitureBanking.EligibleOverdraftAccounts
> = core.serialization.object({
    items: core.serialization.unknown(),
    maximumOverdraftAccounts: core.serialization.number(),
    nextPageUrl: core.serialization.property("nextPage_url", core.serialization.string().optional()),
    start: core.serialization.string().optional(),
    limit: core.serialization.number(),
});

export declare namespace EligibleOverdraftAccounts {
    interface Raw {
        items?: unknown;
        maximumOverdraftAccounts: number;
        nextPage_url?: string | null;
        start?: string | null;
        limit: number;
    }
}
