/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const EligibleOverdraftAccountItem: core.serialization.ObjectSchema<
    serializers.EligibleOverdraftAccountItem.Raw,
    ApitureBanking.EligibleOverdraftAccountItem
> = core.serialization.lazyObject(async () => (await import("..")).OverdraftAccountFields);

export declare namespace EligibleOverdraftAccountItem {
    type Raw = serializers.OverdraftAccountFields.Raw;
}
