/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const ExternalAccountVerificationMethod: core.serialization.Schema<
    serializers.ExternalAccountVerificationMethod.Raw,
    ApitureBanking.ExternalAccountVerificationMethod
> = core.serialization.enum_(["instant", "microDeposits", "manual"]);

export declare namespace ExternalAccountVerificationMethod {
    type Raw = "instant" | "microDeposits" | "manual";
}
