/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const FullAccountNumber: core.serialization.Schema<
    serializers.FullAccountNumber.Raw,
    ApitureBanking.FullAccountNumber
> = core.serialization.string();

export declare namespace FullAccountNumber {
    type Raw = string;
}
