/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const FullAccountPermissions: core.serialization.ObjectSchema<
    serializers.FullAccountPermissions.Raw,
    ApitureBanking.FullAccountPermissions
> = core.serialization
    .object({
        manageJointOwners: core.serialization.boolean(),
        manageOverdraftAccounts: core.serialization.boolean(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("..")).AccountPermissions));

export declare namespace FullAccountPermissions {
    interface Raw extends serializers.AccountPermissions.Raw {
        manageJointOwners: boolean;
        manageOverdraftAccounts: boolean;
    }
}
