/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const JointOwnerInvitation: core.serialization.ObjectSchema<
    serializers.JointOwnerInvitation.Raw,
    ApitureBanking.JointOwnerInvitation
> = core.serialization
    .object({
        id: core.serialization.lazy(async () => (await import("..")).ReadOnlyResourceId),
    })
    .extend(core.serialization.lazyObject(async () => (await import("..")).AbstractBody))
    .extend(core.serialization.lazyObject(async () => (await import("..")).JointOwnerInvitationFields));

export declare namespace JointOwnerInvitation {
    interface Raw extends serializers.AbstractBody.Raw, serializers.JointOwnerInvitationFields.Raw {
        id: serializers.ReadOnlyResourceId.Raw;
    }
}
