/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const MonetaryValue: core.serialization.Schema<serializers.MonetaryValue.Raw, ApitureBanking.MonetaryValue> =
    core.serialization.string();

export declare namespace MonetaryValue {
    type Raw = string;
}
