/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const OverdraftAccountFields: core.serialization.ObjectSchema<
    serializers.OverdraftAccountFields.Raw,
    ApitureBanking.OverdraftAccountFields
> = core.serialization.object({
    id: core.serialization.lazy(async () => (await import("..")).ResourceId).optional(),
    label: core.serialization.string().optional(),
    maskedNumber: core.serialization.lazy(async () => (await import("..")).MaskedAccountNumber).optional(),
});

export declare namespace OverdraftAccountFields {
    interface Raw {
        id?: serializers.ResourceId.Raw | null;
        label?: string | null;
        maskedNumber?: serializers.MaskedAccountNumber.Raw | null;
    }
}
