/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const ReadOnlyResourceId: core.serialization.Schema<
    serializers.ReadOnlyResourceId.Raw,
    ApitureBanking.ReadOnlyResourceId
> = core.serialization.lazy(async () => (await import("..")).ResourceId);

export declare namespace ReadOnlyResourceId {
    type Raw = serializers.ResourceId.Raw;
}
