/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const ReadOnlyTimestamp: core.serialization.Schema<
    serializers.ReadOnlyTimestamp.Raw,
    ApitureBanking.ReadOnlyTimestamp
> = core.serialization.string();

export declare namespace ReadOnlyTimestamp {
    type Raw = string;
}
