/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const ResourceId: core.serialization.Schema<serializers.ResourceId.Raw, ApitureBanking.ResourceId> =
    core.serialization.string();

export declare namespace ResourceId {
    type Raw = string;
}
