/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const TimestampFields: core.serialization.ObjectSchema<
    serializers.TimestampFields.Raw,
    ApitureBanking.TimestampFields
> = core.serialization.object({
    createdAt: core.serialization.string().optional(),
    updatedAt: core.serialization.string().optional(),
});

export declare namespace TimestampFields {
    interface Raw {
        createdAt?: string | null;
        updatedAt?: string | null;
    }
}
