/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const TimeZoneId: core.serialization.Schema<serializers.TimeZoneId.Raw, ApitureBanking.TimeZoneId> =
    core.serialization.string();

export declare namespace TimeZoneId {
    type Raw = string;
}
