/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const TransferDateRestrictionType: core.serialization.Schema<
    serializers.TransferDateRestrictionType.Raw,
    ApitureBanking.TransferDateRestrictionType
> = core.serialization.enum_(["pastDate", "pastCutoffTime", "riskRestricted", "holiday", "closure", "other"]);

export declare namespace TransferDateRestrictionType {
    type Raw = "pastDate" | "pastCutoffTime" | "riskRestricted" | "holiday" | "closure" | "other";
}
