/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const TransactionFields: core.serialization.ObjectSchema<
    serializers.TransactionFields.Raw,
    ApitureBanking.TransactionFields
> = core.serialization.object({
    id: core.serialization.string(),
    type: core.serialization.lazy(async () => (await import("..")).TransactionType),
    subtype: core.serialization.lazy(async () => (await import("..")).TransactionSubType),
    occurredOn: core.serialization.string(),
    createdOn: core.serialization.string().optional(),
    postedOn: core.serialization.string().optional(),
    amount: core.serialization.lazy(async () => (await import("..")).CreditOrDebitValue),
    posted: core.serialization.boolean().optional(),
    balance: core.serialization.lazy(async () => (await import("..")).CreditOrDebitValue).optional(),
    memo: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
    category: core.serialization.lazyObject(async () => (await import("..")).TransactionCategorization).optional(),
    merchant: core.serialization.lazyObject(async () => (await import("..")).TransactionMerchant).optional(),
    check: core.serialization.lazyObject(async () => (await import("..")).TransactionCheck).optional(),
});

export declare namespace TransactionFields {
    interface Raw {
        id: string;
        type: serializers.TransactionType.Raw;
        subtype: serializers.TransactionSubType.Raw;
        occurredOn: string;
        createdOn?: string | null;
        postedOn?: string | null;
        amount: serializers.CreditOrDebitValue.Raw;
        posted?: boolean | null;
        balance?: serializers.CreditOrDebitValue.Raw | null;
        memo?: string | null;
        description?: string | null;
        category?: serializers.TransactionCategorization.Raw | null;
        merchant?: serializers.TransactionMerchant.Raw | null;
        check?: serializers.TransactionCheck.Raw | null;
    }
}
