/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const TransferFields: core.serialization.ObjectSchema<
    serializers.TransferFields.Raw,
    ApitureBanking.TransferFields
> = core.serialization.object({
    amount: core.serialization.lazy(async () => (await import("..")).MonetaryValue).optional(),
    sourceAccount: core.serialization.lazyObject(async () => (await import("..")).TransferAccountReference).optional(),
    targetAccount: core.serialization.lazyObject(async () => (await import("..")).TransferAccountReference).optional(),
    memo: core.serialization.string().optional(),
});

export declare namespace TransferFields {
    interface Raw {
        amount?: serializers.MonetaryValue.Raw | null;
        sourceAccount?: serializers.TransferAccountReference.Raw | null;
        targetAccount?: serializers.TransferAccountReference.Raw | null;
        memo?: string | null;
    }
}
