/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const TransferRecurrenceType: core.serialization.Schema<
    serializers.TransferRecurrenceType.Raw,
    ApitureBanking.TransferRecurrenceType
> = core.serialization.enum_(["fixed", "variable"]);

export declare namespace TransferRecurrenceType {
    type Raw = "fixed" | "variable";
}
