/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const TransactionType: core.serialization.Schema<
    serializers.TransactionType.Raw,
    ApitureBanking.TransactionType
> = core.serialization.enum_(["balance", "debit", "credit"]);

export declare namespace TransactionType {
    type Raw = "balance" | "debit" | "credit";
}
