/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const TransferItemSchedule: core.serialization.ObjectSchema<
    serializers.TransferItemSchedule.Raw,
    ApitureBanking.TransferItemSchedule
> = core.serialization
    .object({
        debitsOn: core.serialization.string().optional(),
        creditsOn: core.serialization.string().optional(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("..")).TransferSchedule));

export declare namespace TransferItemSchedule {
    interface Raw extends serializers.TransferSchedule.Raw {
        debitsOn?: string | null;
        creditsOn?: string | null;
    }
}
