/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const TransactionCategory: core.serialization.ObjectSchema<
    serializers.TransactionCategory.Raw,
    ApitureBanking.TransactionCategory
> = core.serialization
    .object({
        type: core.serialization.lazy(async () => (await import("..")).TransactionCategoryType),
    })
    .extend(core.serialization.lazyObject(async () => (await import("..")).AbstractBody))
    .extend(core.serialization.lazyObject(async () => (await import("..")).TransactionCategorization));

export declare namespace TransactionCategory {
    interface Raw extends serializers.AbstractBody.Raw, serializers.TransactionCategorization.Raw {
        type: serializers.TransactionCategoryType.Raw;
    }
}
