/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ApitureBanking from "../../api";
import * as core from "../../core";

export const TransactionSubType: core.serialization.Schema<
    serializers.TransactionSubType.Raw,
    ApitureBanking.TransactionSubType
> = core.serialization.enum_(["check", "other"]);

export declare namespace TransactionSubType {
    type Raw = "check" | "other";
}
