/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as ApitureBanking from "../../../../../api";
import * as core from "../../../../../core";

export const TransferPatch: core.serialization.Schema<
    serializers.TransferPatch.Raw,
    Omit<ApitureBanking.TransferPatch, "challenge">
> = core.serialization
    .object({
        schedule: core.serialization.lazyObject(async () => (await import("../../../..")).TransferSchedule).optional(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../../..")).AbstractBody))
    .extend(core.serialization.lazyObject(async () => (await import("../../../..")).TransferFields));

export declare namespace TransferPatch {
    interface Raw extends serializers.AbstractBody.Raw, serializers.TransferFields.Raw {
        schedule?: serializers.TransferSchedule.Raw | null;
    }
}
