/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ApitureApi } from "@fern-api/apiture";
import * as core from "../../../../core";

export const ProductReference: core.serialization.ObjectSchema<
    serializers.ProductReference.Raw,
    ApitureApi.ProductReference
> = core.serialization.object({
    type: core.serialization.lazy(async () => (await import("../../..")).ProductType),
    code: core.serialization.string(),
    label: core.serialization.string(),
    description: core.serialization.string(),
});

export declare namespace ProductReference {
    interface Raw {
        type: serializers.ProductType.Raw;
        code: string;
        label: string;
        description: string;
    }
}
