/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The monetary value representing a credit (positive amounts with no prefix or a `+` prefix) or debit (negative amounts with a `-` prefix). The numeric value is  represented as a string so that it can be exact with no loss of precision.<br>The schema `creditOrDebitValue` was added on version `0.4.0` of the API.
 */
export type CreditOrDebitValue = string;
