/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A readonly or derived timestamp (an instant in time) formatted in [RFC 3339](https://tools.ietf.org/html/rfc3339) `date-time` UTC format: `YYYY-MM-DDThh:mm:ss.sssZ`.
 */
export type ReadOnlyTimestamp = Date;
