/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * For recurring transfers, the interval at which the money movement recurs. <strong><code>transferFrequency</code></strong> strings may have one of the following [enumerated values](https://dx.apiture.com/docs/api-documentation/concepts/label-groups#enumerations): <table> <tr>
 *   <th>Value</th><th>Description</th>
 * </tr> <tr>
 *     <td><strong><code>once</code></strong></td><td>Once: <p>Transfer does not repeat</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>occasional</code></strong></td><td>Occasional: <p>Transfer recurs but without a new scheduled date</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>daily</code></strong></td><td>Daily: <p>Repeat daily on business days</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>weekly</code></strong></td><td>Weekly: <p>Repeat weekly</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>biweekly</code></strong></td><td>biweekly: <p>Repeat every two weeks (26 times a year)</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>semimonthly</code></strong></td><td>Semimonthly: <p>Repeat twice a month (24 times a year)</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>monthly</code></strong></td><td>Monthly: <p>Repeat monthly</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>monthlyFirstDay</code></strong></td><td>Monthly First Day: <p>Repeat on the first business day of the month</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>monthlyLastDay</code></strong></td><td>Monthly Last Day: <p>Repeat on the last business day of the month</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>bimonthly</code></strong></td><td>Bimonthly: <p>Repeat every other month</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>quarterly</code></strong></td><td>Quarterly: <p>Repeat quarterly (four times a year)</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>semiyearly</code></strong></td><td>Semiyearly: <p>Repeat every six months (twice a year)</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>yearly</code></strong></td><td>Yearly: <p>Repeat once every year</p>
 * </td>
 *     </tr>
 * </table>
 *
 */
export type TransferFrequency =
    | "once"
    | "occasional"
    | "daily"
    | "weekly"
    | "biweekly"
    | "semimonthly"
    | "monthly"
    | "monthlyFirstDay"
    | "monthlyLastDay"
    | "bimonthly"
    | "quarterly"
    | "semiyearly"
    | "yearly";

export const TransferFrequency = {
    Once: "once",
    Occasional: "occasional",
    Daily: "daily",
    Weekly: "weekly",
    Biweekly: "biweekly",
    Semimonthly: "semimonthly",
    Monthly: "monthly",
    MonthlyFirstDay: "monthlyFirstDay",
    MonthlyLastDay: "monthlyLastDay",
    Bimonthly: "bimonthly",
    Quarterly: "quarterly",
    Semiyearly: "semiyearly",
    Yearly: "yearly",
} as const;
