/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Accounts } from "./api/resources/accounts/client/Client";
import { Institutions } from "./api/resources/institutions/client/Client";
import { Transactions } from "./api/resources/transactions/client/Client";
import { Transfers } from "./api/resources/transfers/client/Client";

export declare namespace ApitureClient {
    interface Options {
        environment?: environments.ApitureEnvironment | string;
        acessToken: core.Supplier<string>;
        apiKey?: core.Supplier<string | undefined>;
    }
}

export class ApitureClient {
    constructor(protected readonly options: ApitureClient.Options) {}

    protected _accounts: Accounts | undefined;

    public get accounts(): Accounts {
        return (this._accounts ??= new Accounts(this.options));
    }

    protected _institutions: Institutions | undefined;

    public get institutions(): Institutions {
        return (this._institutions ??= new Institutions(this.options));
    }

    protected _transactions: Transactions | undefined;

    public get transactions(): Transactions {
        return (this._transactions ??= new Transactions(this.options));
    }

    protected _transfers: Transfers | undefined;

    public get transfers(): Transfers {
        return (this._transfers ??= new Transfers(this.options));
    }
}
