/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const ApitureBankingEnvironment = {
    Default: "https://api.apiture.com/banking",
} as const;

export type ApitureBankingEnvironment = typeof ApitureBankingEnvironment.Default;
