/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Apiture } from "@fern-api/apiture";
import * as core from "../../../../core";

export const AbstractPagedBodyFields: core.serialization.ObjectSchema<
    serializers.AbstractPagedBodyFields.Raw,
    Apiture.AbstractPagedBodyFields
> = core.serialization.object({
    limit: core.serialization.number(),
    nextPageUrl: core.serialization.property("nextPage_url", core.serialization.string().optional()),
});

export declare namespace AbstractPagedBodyFields {
    interface Raw {
        limit: number;
        nextPage_url?: string | null;
    }
}
