/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Apiture } from "@fern-api/apiture";
import * as core from "../../../../core";

export const AbstractBody: core.serialization.ObjectSchema<serializers.AbstractBody.Raw, Apiture.AbstractBody> =
    core.serialization.object({});

export declare namespace AbstractBody {
    interface Raw {}
}
