/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Apiture } from "@fern-api/apiture";
import * as core from "../../../../core";

export const AbstractPagedBody: core.serialization.ObjectSchema<
    serializers.AbstractPagedBody.Raw,
    Apiture.AbstractPagedBody
> = core.serialization
    .object({
        start: core.serialization.string().optional(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).AbstractBody))
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).AbstractPagedBodyFields));

export declare namespace AbstractPagedBody {
    interface Raw extends serializers.AbstractBody.Raw, serializers.AbstractPagedBodyFields.Raw {
        start?: string | null;
    }
}
