/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ApitureApi } from "@fern-api/apiture";
import * as core from "../../../../core";

export const DateRange: core.serialization.Schema<serializers.DateRange.Raw, ApitureApi.DateRange> =
    core.serialization.string();

export declare namespace DateRange {
    type Raw = string;
}
