/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ApitureApi } from "@fern-api/apiture";
import * as core from "../../../../core";

export const ReadOnlyTimestamp: core.serialization.Schema<
    serializers.ReadOnlyTimestamp.Raw,
    ApitureApi.ReadOnlyTimestamp
> = core.serialization.date();

export declare namespace ReadOnlyTimestamp {
    type Raw = string;
}
