/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Apiture } from "@fern-api/apiture";
import * as core from "../../../../core";

export const ResourceId: core.serialization.Schema<serializers.ResourceId.Raw, Apiture.ResourceId> =
    core.serialization.string();

export declare namespace ResourceId {
    type Raw = string;
}
