/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ApitureApi } from "@fern-api/apiture";
import * as core from "../../../../core";

export const AccountAllowsFilter: core.serialization.Schema<
    serializers.AccountAllowsFilter.Raw,
    ApitureApi.AccountAllowsFilter
> = core.serialization.enum_([
    "billPay",
    "transferFrom",
    "transferTo",
    "mobileCheckDeposit",
    "view",
    "viewCards",
    "manageCards",
]);

export declare namespace AccountAllowsFilter {
    type Raw = "billPay" | "transferFrom" | "transferTo" | "mobileCheckDeposit" | "view" | "viewCards" | "manageCards";
}
