/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Apiture } from "@fern-api/apiture";
import * as core from "../../../../core";

export const AccountLocation: core.serialization.Schema<serializers.AccountLocation.Raw, Apiture.AccountLocation> =
    core.serialization.enum_(["internal", "external", "outside"]);

export declare namespace AccountLocation {
    type Raw = "internal" | "external" | "outside";
}
