/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Apiture } from "@fern-api/apiture";
import * as core from "../../../../core";

export const AccountPermissions: core.serialization.ObjectSchema<
    serializers.AccountPermissions.Raw,
    Apiture.AccountPermissions
> = core.serialization.object({
    billPay: core.serialization.boolean(),
    mobileCheckDeposit: core.serialization.boolean(),
    transferFrom: core.serialization.boolean(),
    transferTo: core.serialization.boolean(),
    view: core.serialization.boolean(),
    viewCards: core.serialization.boolean(),
    manageCards: core.serialization.boolean(),
});

export declare namespace AccountPermissions {
    interface Raw {
        billPay: boolean;
        mobileCheckDeposit: boolean;
        transferFrom: boolean;
        transferTo: boolean;
        view: boolean;
        viewCards: boolean;
        manageCards: boolean;
    }
}
