/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Apiture } from "@fern-api/apiture";
import * as core from "../../../../core";

export const AchSecCode: core.serialization.Schema<serializers.AchSecCode.Raw, Apiture.AchSecCode> =
    core.serialization.enum_(["arc", "boc", "ccd", "cie", "ctx", "pop", "ppd", "rck", "tel", "web"]);

export declare namespace AchSecCode {
    type Raw = "arc" | "boc" | "ccd" | "cie" | "ctx" | "pop" | "ppd" | "rck" | "tel" | "web";
}
