/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ApitureApi } from "@fern-api/apiture";
import * as core from "../../../../core";

export const JointOwnerInvitationFields: core.serialization.ObjectSchema<
    serializers.JointOwnerInvitationFields.Raw,
    ApitureApi.JointOwnerInvitationFields
> = core.serialization.object({
    firstName: core.serialization.string(),
    lastName: core.serialization.string(),
    taxId: core.serialization.string().optional(),
    sharedSecret: core.serialization.string(),
    emailAddress: core.serialization.string(),
    disallowDebitCardAccess: core.serialization.boolean().optional(),
});

export declare namespace JointOwnerInvitationFields {
    interface Raw {
        firstName: string;
        lastName: string;
        taxId?: string | null;
        sharedSecret: string;
        emailAddress: string;
        disallowDebitCardAccess?: boolean | null;
    }
}
