/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Apiture } from "@fern-api/apiture";
import * as core from "../../../../core";

export const OverdraftProtectionFields: core.serialization.ObjectSchema<
    serializers.OverdraftProtectionFields.Raw,
    Apiture.OverdraftProtectionFields
> = core.serialization.object({
    accounts: core.serialization.unknown().optional(),
});

export declare namespace OverdraftProtectionFields {
    interface Raw {
        accounts?: unknown | null;
    }
}
